version: '3.1'
services:
  kitty-split:
    build: ./
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - "80:8080"
    volumes:
      - "/Users/p.v.gordeev/tinkoff/meetup/kitty_split/yc-db:/yc-db"
    environment:
      - SPRING_ACTIVE_PROFILES=yc-postgres
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_PROPERTIES_SSL_ROOT_CERT=/yc-db/db-root.crt
      - OPEN_EXCHANGE_BASE_URL=http://openexchangerates.org/api
      - OPEN_EXCHANGE_APP_ID=${OPEN_EXCHANGE_APP_ID}

  db:
    image: postgres:14-alpine
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kitty_split
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
