version: '3.1'
services:
  kitty-split:
    build: ./
    depends_on:
      - db
    links:
      - "db:database"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    ports:
      - "80:${PORT}"
    environment:
      - JAVA_OPTS="-server -Xms200m -Xmx400m -Dfile.encoding=UTF-8 -Duser.country=RU -Duser.language=ru -XX:+UseG1GC -XX:ActiveProcessorCount=2 -XX:+AlwaysActAsServerClassMachine"
      - SERVER_PORT=${PORT}
      - SPRING_PROFILES_ACTIVE=yc-postgres
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_PROPERTIES_SSL_ROOT_CERT=/yc-db/db-root.crt
      - OPEN_EXCHANGE_BASE_URL=http://openexchangerates.org/api
      - OPEN_EXCHANGE_APP_ID=${OPEN_EXCHANGE_APP_ID}

  db:
    image: postgres:14-alpine
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kitty_split
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
