defaults:
  time.zone: Europe/Moscow

springfox:
  documentation:
    enabled: ${spring.swagger.enabled}

external:
  open.exchange:
    base-url: ${OPEN_EXCHANGE_BASE_URL}
    app-id: ${OPEN_EXCHANGE_APP_ID}

spring:
  swagger:
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    format:
      offset-date-time: "yyyy-MM-dd'T'HH:mmXXX"
      big-decimal-scale: 5
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
